### ISSUE TITLE
Commander lock bis_fnc_showNotification called with CBA_fnc_globalExecute

### ISSUE THREAD

**Issue by kneegrew** [Neefay/BromA-A3-Framework-Mark3#19]
Using CBA_fnc_globalExecute with a high amount of players might cause issues due to the amount of code sent, don't you think?

Why not use a waitunitl on each client instead, which will be triggerd by a publicvariable instead?

**Comment by Neefay** [comment]
I'm wondering about this one, dude.

The issue here is that if we broadcast commands over the network, things might get laggy at a higher player count, which is true. However the suggestion of having the warnings display client-side with a waitUntil would also depend on variables being broadcast over the network, which in the end basically amounts for the same problem.

It's difficult to work on this for two reasons: like I said, it might not work as expected, and second it will be a lot of work to refactor all the code which currently works.

**Comment by xJenny99x** [comment]
Yes, but it's easier to broadcast a single publicvariable to 50 clients than it's to broadcast a complicated globalExecute over 20 clients. Because a single variable is less bytes to send than a line of code.


But it's nothing urgent or important as we don't get that many players
